### PR TITLE
Italian language .po files for bareos-webui

### PR DESCRIPTION
**Pull request by chown-me**
Here are the .po files containing the strings translated into Italian.

### CODE REVIEW

**Comment by blu-IT** [comment]
Thanks! If you need further support for italian translation - contact me ;-)

**Comment by fbergkemper** [comment]
Internal merge done, push to public upcoming friday.
Thanks a lot for the contribution.

**Comment by fbergkemper** [comment]
If you as a contributor want to get mentioned in the authors file with your real name, please let us know.

**Comment by chown-me** [comment]
@fbergkemper Sure, no problem with that go ahead: Alessandro Rigopoulos , Thank you ;-)

**Pull request merged**
